Tarefa2/fornecedores/urls.py
from .views import (FornecedoreListView, FornecedoreCreateView, FornecedoreDetailView,
                    FornecedoreUpdateView, FornecedoreDeleteView, handler404,
                    handler500, enviaremail)
from django.urls import path
from .apps import ControledefornecedoresConfig

app_name = ControledefornecedoresConfig.name

urlpatterns = [
    path('add/', FornecedoreCreateView.as_view(), name='add'),
    path('list', FornecedoreListView.as_view(), name='list'),
    path('<int:pk>/detail/', FornecedoreDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', FornecedoreUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', FornecedoreDeleteView.as_view(), name='delete'),
    path('email/', enviaremail, name='enviar-email'),
]

handler404 = handler404
handler500 = handler500

Tarefa2/produtos/urls.py
from .views import (ProdutoDeleteView, ProdutoDetailView, ProdutoUpdateView,
                    ProdutoCreateView, ProdutoListView)
from django.urls import path
from .apps import ProdutosConfig

app_name = ProdutosConfig.name
urlpatterns = [
    path('', ProdutoListView.as_view(), name='list'),
    path('add/', ProdutoCreateView.as_view(), name='add'),
    path('<int:pk>/detail/', ProdutoDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', ProdutoUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', ProdutoDeleteView.as_view(), name='delete')


]

Tarefa2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include('Tarefa2.fornecedores.urls', namespace='fornecedores')),
    path('produtos', include('Tarefa2.produtos.urls', namespace='produtos')),
    path('', TemplateView.as_view(template_name="index.html"))
]

Tarefa2/fornecedores/models.py
from django.db import models

class Fornecedor(models.Model):
    nome = models.CharField('Nome', max_length=30, null=True,blank=True)
    CNPJ = models.PositiveIntegerField('CNPJ',null=True,blank=True)
    endereco = models.CharField('Endereço',max_length=30,null=True,blank=True)
    TIPO = ((1, 'Ativo'),(2, 'Inativo'))
    tipo = models.PositiveIntegerField(verbose_name='Tipo', choices= TIPO)
    email = models.EmailField(default='',max_length=30,null=True,blank=True)
    STATUS = ((0, 'Não Faturado'),(1, 'Faturado'),(2, 'Faturado e Enviado'))
    status = models.PositiveIntegerField(verbose_name='Status do Pedido',default=True, choices= STATUS)

    def __str__(self):
        return self.nome

Tarefa2/produtos/models.py
from django.db import models
class Produto(models.Model):
    codigo = models.CharField('Código',max_length=20,null=True,blank=True)
    descricao = models.CharField('Descrição',max_length=80,null=True,blank=True)
    valorunitario = models.DecimalField('Valor Unitário',decimal_places=2,max_digits=4,null=True,blank=True)
    quantidadedeestoque = models.DecimalField('Quantidade de Estoque',decimal_places=2,max_digits=4,null=True,blank=True)

    def __str__(self):
        return self.nome

Tarefa2/fornecedores/forms.py
from django import forms
from .models import Fornecedor

class FornecedorForm(forms.ModelForm):
    class Meta:
        model= Fornecedor
        fields = '__all__'

Tarefa2/produtos/forms.py
from django import forms
from .models import Produto

class ProdutoForm(forms.ModelForm):
    class Meta:
        model= Produto
        fields = '__all__'

Tarefa2/fornecedores/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Fornecedor
from .forms import FornecedorForm
from django.urls import reverse_lazy
from django.shortcuts import render
from django.core.mail import send_mail



class FornecedoreListView(ListView):
    def get_context_object_name(self, object_list):
        return 'controle_list'

    def get_template_names(self):
        return 'fornecedor_list.html'

    def get_queryset(self):
        return Fornecedor.objects.all()


class FornecedoreCreateView(CreateView):
    model = Fornecedor

    def get_template_names(self):
        return 'fornecedor_form.html'

    def get_success_url(self):
        return reverse_lazy('fornecedores:list')

    def get_form_class(self):
        return FornecedorForm


class FornecedoreUpdateView(UpdateView):
    model = Fornecedor

    def get_template_names(self):
        return 'fornecedor_form.html'

    def get_success_url(self):
        return reverse_lazy('fornecedores:list')

    def get_form_class(self):
        return FornecedorForm


class FornecedoreDetailView(DetailView):
    model = Fornecedor

    def get_template_names(self):
        return 'fornecedor_detail.html'


class FornecedoreDeleteView(DeleteView):
    model = Fornecedor

    def get_template_names(self):
        return 'fornecedor_confim_delete.html'

    def get_success_url(self):
        return reverse_lazy('fornecedores:list')


def handler404(request):
    return render(request, '404.html', status=404)


def handler500(request):
    return render(request, '500.html', status=500)


def enviaremail(request):
    send_mail(
        subject='Assunto:',
        message='Pedido realizado com sucesso.',
        from_email='de@example.com',
        recipient_list=['para@example.com'],
        fail_silently=False,
    )
    return HttpResponseRedirect(reverse_lazy('fornecedores:list'))

Tarefa2/produtos/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Produto
from .forms import ProdutoForm
from django.urls import reverse_lazy
from django.shortcuts import render

class ProdutoListView(ListView):
    def get_context_object_name(self, object_list):
        return 'listp'
    def get_template_names(self):
        return 'produto_list.html'
    def get_queryset(self):
        return Produto.objects.all()

class ProdutoCreateView(CreateView):
    model = Produto
    def get_template_names(self):
        return'produto_form.html'
    def get_success_url(self):
        return reverse_lazy('produto:list')
    def get_form_class(self):
        return ProdutoForm

class ProdutoUpdateView(UpdateView):
    model = Produto
    def get_template_names(self):
        return'produto_form.html'
    def get_success_url(self):
        return reverse_lazy('produto:list')
    def get_form_class(self):
        return ProdutoForm


class ProdutoDetailView(DetailView):
    model = Produto
    def get_template_names(self):
        return 'produto_detail.html'

class ProdutoDeleteView(DeleteView):
    model = Produto
    def get_template_names(self):
        return 'produto_confim_delete.html'
    def get_success_url(self):
        return reverse_lazy('produto:list')

Tarefa2/fornecedores/templates/fornecedor_confim_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Delete</button>
</form>


</body>
</html>

Tarefa2/fornecedores/templates/fornecedor_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Nome: {{ object.nome }}</p>
<p>CNPJ: {{ object.CNPJ }}</p>
<p>Endereço: {{ object.Endereço }}</p>


<a href="{% url 'fornecedores:list' %}">Listagem</a>
<a href="{% url 'fornecedores:edit' pk=object.id %}">Editar</a>
<a href="{% url 'fornecedores:delete' pk=object.id %}">Excluir</a>
</body>
</html>

Tarefa2/fornecedores/templates/fornecedor_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Salvar</button>
</form>


</body>
</html>

Tarefa2/fornecedores/templates/fornecedor_list.html
<!DOCTYPE html>

{% load tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Faça o cadastro de Fornecedores</h1>
<table>
    <thead>
    <tr>
        <th>Nome</th>
        <th>CNPJ</th>
        <th>Endereço</th>
        <th>Tipo</th>
        <th>Email</th>
        <th>Status</th>
    </tr>
    </thead>
<tbody>
{% for controle in controle_list %}
<tr>
    <td>
        <a href="{% url 'fornecedores:detail' controle.id %}">{{ controle.nome }}</a>
    </td>
    <td>{{ controle.CNPJ }}</td>
    <td>{{ controle.endereco }}</td>
    <td>{{ controle.tipo|tipo_choices }}</td>
    <td>{{ controle.email }}</td>
    <td>{{ controle.status }}</td>

</tr>
{% endfor %}
</tbody>
</table>
<a href="{% url 'fornecedores:add' %}">Novo</a></br>
<a href="{% url 'fornecedores:enviar-email' %}">Fazer Pedido</a>
</body>
</html>

Tarefa2/produtos/templates/produto_confim_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Delete</button>
</form>


</body>
</html>

Tarefa2/produtos/templates/produto_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Código: {{ object.codigo }}</p>
<p>Descrição: {{ object.descricao }}</p>
<p>Valor Unitário: {{ object.valorunitario }}</p>


<a href="{% url 'produto:list' %}">Listagem</a>
<a href="{% url 'produto:edit' pk=object.id %}">Editar</a>
<a href="{% url 'produto:delete' pk=object.id %}">Excluir</a>
</body>
</html>

Tarefa2/produtos/templates/produto_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Salvar</button>
</form>


</body>
</html>

Tarefa2/produtos/templates/produto_list.html
<!DOCTYPE html>

{% load tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Faça o cadastro de Produtos</h1>
<table>
    <thead>
    <tr>
        <th>Código</th>
        <th>Descrição</th>
        <th>Valor Unitário</th>
        <th>Quantidade de Estoque</th>
    </tr>
    </thead>
<tbody>
{% for produto in listp %}
<tr>
    <td>
        <a href="{% url 'produto:detail' produto.id %}">{{ produto.nome }}</a>
    </td>
    <td>{{ produto.codigo }}</td>
    <td>{{ produto.descricao }}</td>
    <td>{{ produto.valorunitario }}</td>
    <td>{{ produto.quantidadedeestoque }}</td>

</tr>
{% endfor %}
</tbody>
</table>
<a href="{% url 'produtos:add' %}">Novo</a>
</body>
</html>

Tarefa2/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>

<h1>Escolha o tipo de Cadastro</h1>
<a href="{% url 'fornecedores:list' %}">Cadastro de Fornecedores</a>
<a href="{% url 'produtos:list' %}">Cadastro de Produtos</a>
</body>
</html>